### ISSUE TITLE
Error in the path of the predict step!

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/BAD_Mutations#30]
Paul and I tried to test with interactive python with the "_MAS.fasta" file, and it seems the script can not find the absolute path of this file.
```python
Traceback (most recent call last):
  File "/home/morrellp/llei/BAD_Mutations/BAD_Mutations.py", line 335, in <module>
    main()
  File "/home/morrellp/llei/BAD_Mutations/BAD_Mutations.py", line 315, in main
    out = predict(arguments_valid, loglevel)
  File "/home/morrellp/llei/BAD_Mutations/BAD_Mutations.py", line 250, in predict
    lrt.prepare_hyphy_inputs()
  File "/panfs/roc/groups/9/morrellp/llei/BAD_Mutations/lrt_predict/Predict/predict.py", line 102, in prepare_hyphy_inputs
    infile.write(os.path.abspath(self.nmsa) + '\n')
  File "/soft/python2/2.7.8/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/soft/python2/2.7.8/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'MultipleSeqAlignment' object has no attribute 'startswith'
```

**Comment by TomJKono** [comment]
Fixed in 9f55398ecc8ace1a46a7afdaf8c39ca412576352

`predict.py` was trying to get the path for a `MultipleSequenceAlignment` object, when it should have been trying to get the path for a `str` object representing a filename
