### ISSUE TITLE
The XML document has moved 

### ISSUE THREAD

**Issue by hubner-lab** [MorrellLAB/BAD_Mutations#50]
Hi, 
when i'm using "Fetch" i get this error:

DEBUG	The XML I got was 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=Phytozome">here</a>.</p>
</body></html>

===2020-01-26 12:56:30,035 - lrt_predict.Fetch.fetch===
DEBUG	The XML I got was 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=Phytozome">here</a>.</p>
</body></html>

Traceback (most recent call last):
  File "/mnt/data/Tools/BAD_Mutations-Python3/BAD_Mutations/BAD_Mutations.py", line 382, in <module>
    main()
  File "/mnt/data/Tools/BAD_Mutations-Python3/BAD_Mutations/BAD_Mutations.py", line 348, in main
    fetch(arguments_valid, loglevel)
  File "/mnt/data/Tools/BAD_Mutations-Python3/BAD_Mutations/BAD_Mutations.py", line 110, in fetch
    phy.get_xml_urls()
  File "/mnt/data/Tools/BAD_Mutations-Python3/BAD_Mutations/lrt_predict/Fetch/phytozome.py", line 168, in get_xml_urls
    xml_tree = ElementTree.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49

i didn't manage to redirect the phytosome.py script to the correct XML, any suggestions?

**Comment by conJUSTover** [comment]
I had this error too, and couldn't figure out a fix. But if you log into phytozome, you can download all the files from phytozome12 (I would recommend clicking all the files you want, and downloading them as a zipped file). The species list is in the file lrt_predict/Fetch/phytozome_species.py. Then you can use the --convert-only flag in the fetch subcommand. 

This is a potential manual way around the bug, and it only took me about half an hour to download the files and organize them correctly.

**Comment by dumitru314** [comment]
hi, i have too this problem ... you found some solutions ?
